"""e2e demo · v1.1 · 完整价值链跑通 (T78).

模拟生产场景:
  1. 3 个 user 注册 + login (拿 JWT)
  2. Alice 创建 project (bootstrap owner) + 加 Bob/Carol 为 reviewer/contributor
  3. mock skill_service.distill_skill 模拟自动蒸馏
  4. consent: Alice (owner) + Bob (reviewer) + Carol (contributor) 都签
  5. submit-for-review → Bob approve → skill active
  6. Alice publish → marketplace 可见
  7. Dave 注册 + create proj-2 + import skill (来自 proj-1)
  8. 验证: 新 skill 在 proj-2 / status=draft / source 留痕

整链不 mock 真 HTTP endpoint (TestClient 直调); 仅 mock distill_skill 的 LLM 部分.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.gateway.http_api import api_router
from app.persistence import store as store_module
from app.persistence.store import SqliteStore
from app.schemas.skill import Skill, SkillMetrics
from app.services import skill_service


@pytest.fixture
def fresh_db(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    db_path = tmp_path / "state.sqlite"
    s = SqliteStore(db_path)
    s._apply_schema()
    monkeypatch.setattr(store_module, "_db", s)
    skill_service.reset_registry_for_tests()
    return s


@pytest.fixture
def client(fresh_db) -> TestClient:
    """挂载完整 api_router (含 /api/v1 前缀模拟)."""
    app = FastAPI()
    app.include_router(api_router, prefix="/api/v1")
    return TestClient(app)


def _register(client: TestClient, email: str, display_name: str) -> dict:
    """注册新 user, 返回 {access_token, user_id, headers}."""
    r = client.post(
        "/api/v1/auth/register",
        json={
            "email": email,
            "password": "test-pw-12345678",
            "display_name": display_name,
        },
    )
    assert r.status_code == 201, r.text
    body = r.json()
    return {
        "token": body["access_token"],
        "user_id": body["user"]["id"],
        "headers": {"Authorization": f"Bearer {body['access_token']}"},
        "user": body["user"],
    }


def _make_pending_skill(
    *,
    skill_id="skill-e2e",
    project_id="proj-1",
    contributors: list[str],
) -> Skill:
    """构造一个已经 initialize_pending 的 skill, 替代真 distill_skill (跳 LLM)."""
    from app.services.skill.consent import initialize_pending

    now = datetime.now(timezone.utc)
    skill = Skill(
        id=skill_id,
        project_id=project_id,
        name="auto-distilled-skill",
        version=1,
        skill_md=(
            "---\nname: auto-distilled-skill\ndescription: e2e demo\n---\n"
            "# Auto-distilled skill body\n\n"
            "This skill was auto-generated by the @bot mention pipeline."
        ),
        embedding=None,
        metrics=SkillMetrics(),
        distilled_from=[],
        distilled_at=now,
        last_used_at=None,
        locked=False,
        status="draft",
        parent_skill_id=None,
        contributors=list(contributors),
        consent_required_from=[],
        consent_signed_by=[],
        consent_rejected_by=None,
        consent_expires_at=None,
        review_state="not_submitted",
        review_history=[],
        last_reviewer_id=None,
        last_reviewed_at=None,
        visibility="private",
        published_at=None,
        source_skill_id=None,
        source_project_id=None,
        imported_at=None,
        created_at=now,
        updated_at=now,
    )
    return initialize_pending(skill)


@pytest.mark.asyncio
async def test_e2e_full_value_chain(client, fresh_db):
    """完整价值链:
    register(3 users) → bootstrap project → add members →
    pending_consent skill → 3 sign → review submit → approve → active →
    publish → marketplace → 4th user import → verify.
    """
    # ─── 1. 4 个 user 注册 ───
    alice = _register(client, "alice@e2e.com", "Alice")
    bob = _register(client, "bob@e2e.com", "Bob")
    carol = _register(client, "carol@e2e.com", "Carol")
    dave = _register(client, "dave@e2e.com", "Dave")

    # 用 alice 的 user_id 模拟 IM contributor identity
    alice_id = alice["user_id"]
    bob_id = bob["user_id"]
    carol_id = carol["user_id"]
    dave_id = dave["user_id"]

    # ─── 2. Alice bootstrap proj-1 → 加 Bob (reviewer) + Carol (contributor) ───
    r = client.post(
        "/api/v1/projects/proj-1/members",
        json={"user_id": "ignored", "role": "owner"},
        headers=alice["headers"],
    )
    assert r.status_code == 201
    assert r.json()["role"] == "owner"
    assert r.json()["user_id"] == alice_id

    # 加 bob (reviewer)
    r = client.post(
        "/api/v1/projects/proj-1/members",
        json={"user_id": bob_id, "role": "reviewer"},
        headers=alice["headers"],
    )
    assert r.status_code == 201

    # 加 carol (contributor)
    r = client.post(
        "/api/v1/projects/proj-1/members",
        json={"user_id": carol_id, "role": "contributor"},
        headers=alice["headers"],
    )
    assert r.status_code == 201

    # 验列表
    r = client.get("/api/v1/projects/proj-1/members", headers=alice["headers"])
    assert r.status_code == 200
    body = r.json()
    assert body["owner_count"] == 1
    assert body["reviewer_count"] == 1
    assert body["contributor_count"] == 1

    # ─── 3. 模拟 @bot 蒸馏 (跳 LLM, 直接 seed pending skill) ───
    skill = _make_pending_skill(
        skill_id="skill-e2e-1",
        project_id="proj-1",
        contributors=[alice_id, bob_id, carol_id],
    )
    # contributors 也作为 consent_required_from
    skill_service.get_registry().add(skill)
    assert skill.status == "pending_contributor_consent"
    assert set(skill.consent_required_from) == {alice_id, bob_id, carol_id}

    # ─── 4. 3 个 contributor 全签 ───
    for actor in (alice, bob, carol):
        r = client.post(
            f"/api/v1/skills/{skill.id}/consent/sign",
            json={"user_id": actor["user_id"], "channel": "web"},
            headers=actor["headers"],
        )
        assert r.status_code == 200, f"sign by {actor['user']['email']}: {r.text}"

    # 验最后一次 sign 触发 all_signed 转 draft
    after_sign = client.get(
        f"/api/v1/skills/{skill.id}", headers=alice["headers"]
    ).json()
    assert after_sign["status"] == "draft"
    assert after_sign["review_state"] == "not_submitted"

    # ─── 5. Alice submit → Bob approve → skill active ───
    r = client.post(
        f"/api/v1/skills/{skill.id}/submit-for-review",
        json={"user_id": alice_id, "note": "ready for review"},
        headers=alice["headers"],
    )
    assert r.status_code == 200
    assert r.json()["review_state"] == "pending_review"

    # Bob (reviewer) approve
    r = client.post(
        f"/api/v1/skills/{skill.id}/review/approve",
        json={"reviewer_id": bob_id, "note": "LGTM"},
        headers=bob["headers"],
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["review_state"] == "approved"
    assert body["status"] == "active"  # ← 自动转 active

    # ─── 6. Alice publish 到 marketplace ───
    r = client.post(
        f"/api/v1/skills/{skill.id}/publish", headers=alice["headers"]
    )
    assert r.status_code == 200
    assert r.json()["visibility"] == "public"

    # marketplace 列表可见
    r = client.get("/api/v1/marketplace/skills")
    assert r.status_code == 200
    market_items = r.json()["items"]
    assert any(it["skill_id"] == skill.id for it in market_items)

    # ─── 7. Dave 创建 proj-2 + import skill ───
    r = client.post(
        "/api/v1/projects/proj-2/members",
        json={"user_id": "ignored", "role": "owner"},
        headers=dave["headers"],
    )
    assert r.status_code == 201

    r = client.post(
        "/api/v1/projects/proj-2/skills/import",
        json={"source_skill_id": skill.id},
        headers=dave["headers"],
    )
    assert r.status_code == 201, r.text
    imported = r.json()

    # ─── 8. 验证 import 结果 ───
    assert imported["project_id"] == "proj-2"
    assert imported["source_skill_id"] == skill.id
    assert imported["source_project_id"] == "proj-1"
    assert imported["status"] == "draft"
    assert imported["review_state"] == "not_submitted"
    assert imported["visibility"] == "private"
    # metrics 重置
    assert imported["metrics"]["usage_count"] == 0
    assert imported["metrics"]["acceptance_count"] == 0
    # consent 字段空 (新项目独立)
    assert imported["contributors"] == []
    assert imported["consent_required_from"] == []
    # 跨 project evolve_chain 断开
    assert imported["parent_skill_id"] is None
    assert imported["version"] == 1


@pytest.mark.asyncio
async def test_e2e_reject_path_blocks_skill(client, fresh_db):
    """单否决路径: 1 个 contributor 拒, skill 冻结 rejected_by_contributor."""
    alice = _register(client, "a@reject.com", "A")
    bob = _register(client, "b@reject.com", "B")

    client.post(
        "/api/v1/projects/p-reject/members",
        json={"user_id": "x", "role": "owner"},
        headers=alice["headers"],
    )
    client.post(
        "/api/v1/projects/p-reject/members",
        json={"user_id": bob["user_id"], "role": "contributor"},
        headers=alice["headers"],
    )

    skill = _make_pending_skill(
        skill_id="skill-rej-1",
        project_id="p-reject",
        contributors=[alice["user_id"], bob["user_id"]],
    )
    skill_service.get_registry().add(skill)

    # Alice 签了
    client.post(
        f"/api/v1/skills/{skill.id}/consent/sign",
        json={"user_id": alice["user_id"], "channel": "web"},
        headers=alice["headers"],
    )
    # Bob 拒
    r = client.post(
        f"/api/v1/skills/{skill.id}/consent/reject",
        json={
            "user_id": bob["user_id"],
            "channel": "web",
            "reason": "属于 HR 敏感讨论, 不宜蒸馏",
        },
        headers=bob["headers"],
    )
    assert r.status_code == 200
    assert r.json()["current_status"] == "rejected_by_contributor"

    # 之后 alice 想 sign 一次更应 409 (skill 已冻结)
    r2 = client.post(
        f"/api/v1/skills/{skill.id}/consent/sign",
        json={"user_id": alice["user_id"], "channel": "web"},
        headers=alice["headers"],
    )
    assert r2.status_code == 409  # 状态非 pending


@pytest.mark.asyncio
async def test_e2e_reviewer_reject_then_resubmit_approve(client, fresh_db):
    """完整 Reviewer cycle: submit → reject → fix → 重提 → approve."""
    alice = _register(client, "a@rv.com", "A")
    bob = _register(client, "b@rv.com", "B")

    client.post(
        "/api/v1/projects/p-rv/members",
        json={"user_id": "x", "role": "owner"},
        headers=alice["headers"],
    )
    client.post(
        "/api/v1/projects/p-rv/members",
        json={"user_id": bob["user_id"], "role": "reviewer"},
        headers=alice["headers"],
    )

    # 直接构造已 draft 的 skill (跳 consent 流程, 测 review 焦点)
    now = datetime.now(timezone.utc)
    skill = Skill(
        id="skill-rv-1", project_id="p-rv", name="rv-demo",
        version=1, skill_md="---\n---\n",
        embedding=None, metrics=SkillMetrics(),
        distilled_from=[], distilled_at=now, last_used_at=None,
        locked=False, status="draft", parent_skill_id=None,
        contributors=[alice["user_id"], bob["user_id"]],
        consent_required_from=[], consent_signed_by=[],
        consent_rejected_by=None, consent_expires_at=None,
        review_state="not_submitted", review_history=[],
        last_reviewer_id=None, last_reviewed_at=None,
        visibility="private", published_at=None,
        source_skill_id=None, source_project_id=None, imported_at=None,
        created_at=now, updated_at=now,
    )
    skill_service.get_registry().add(skill)

    # Alice submit
    r = client.post(
        f"/api/v1/skills/{skill.id}/submit-for-review",
        json={"user_id": alice["user_id"]},
        headers=alice["headers"],
    )
    assert r.status_code == 200

    # Bob reject
    r = client.post(
        f"/api/v1/skills/{skill.id}/review/reject",
        json={
            "reviewer_id": bob["user_id"],
            "reason": "needs more concrete examples",
        },
        headers=bob["headers"],
    )
    assert r.status_code == 200
    assert r.json()["review_state"] == "rejected"

    # Alice 修订 (此处仅 PATCH skill_md, 略)... 重新 submit
    r = client.post(
        f"/api/v1/skills/{skill.id}/submit-for-review",
        json={"user_id": alice["user_id"], "note": "added examples"},
        headers=alice["headers"],
    )
    assert r.status_code == 200
    assert r.json()["review_state"] == "pending_review"

    # Bob approve
    r = client.post(
        f"/api/v1/skills/{skill.id}/review/approve",
        json={"reviewer_id": bob["user_id"]},
        headers=bob["headers"],
    )
    assert r.status_code == 200
    body = r.json()
    assert body["review_state"] == "approved"
    assert body["status"] == "active"

    # 查 history (4 records: submit/reject/submit/approve)
    detail = client.get(
        f"/api/v1/skills/{skill.id}", headers=alice["headers"]
    ).json()
    assert len(detail["review_history"]) == 4
    actions = [r["action"] for r in detail["review_history"]]
    assert actions == ["submit", "reject", "submit", "approve"]


@pytest.mark.asyncio
async def test_e2e_acl_blocks_non_reviewer_approve(client, fresh_db):
    """ACL 边界: contributor 不能 approve."""
    alice = _register(client, "a@acl.com", "A")
    carol = _register(client, "c@acl.com", "C")

    client.post(
        "/api/v1/projects/p-acl/members",
        json={"user_id": "x", "role": "owner"},
        headers=alice["headers"],
    )
    client.post(
        "/api/v1/projects/p-acl/members",
        json={"user_id": carol["user_id"], "role": "contributor"},
        headers=alice["headers"],
    )

    now = datetime.now(timezone.utc)
    skill = Skill(
        id="skill-acl", project_id="p-acl", name="acl-test",
        version=1, skill_md="---\n---\n",
        embedding=None, metrics=SkillMetrics(),
        distilled_from=[], distilled_at=now, last_used_at=None,
        locked=False, status="draft", parent_skill_id=None,
        contributors=[], consent_required_from=[], consent_signed_by=[],
        consent_rejected_by=None, consent_expires_at=None,
        review_state="pending_review",  # 已提交
        review_history=[],
        last_reviewer_id=None, last_reviewed_at=None,
        visibility="private", published_at=None,
        source_skill_id=None, source_project_id=None, imported_at=None,
        created_at=now, updated_at=now,
    )
    skill_service.get_registry().add(skill)

    # Carol (contributor 仅) 试图 approve → 403
    r = client.post(
        f"/api/v1/skills/{skill.id}/review/approve",
        json={"reviewer_id": carol["user_id"]},
        headers=carol["headers"],
    )
    assert r.status_code == 403
    assert "reviewer role" in r.json()["detail"].lower()
